### ISSUE TITLE
As an instructor, I want to create the test so that I can specify one or more real world situations for students to solve.

### ISSUE THREAD

**Issue by MitaliBhiwande** [bakshizaki/sec_test#12]
Tasks:
If a question fits the real world scenario, include it in test.

Test:
Create questions in proper common format which can be included as input.

**Comment by bakshizaki** [comment]
I think the part after so that .. should be some testable action which can be done in our program or related to our program. For example "As an instructor, I want to add new question to the test so I create a new folder and added relevant files to that folder"
Tasks:
* Specify the format, location and name of the files for the question/ answers/ reasons etc.
* Code the program to load files from this location.
Tests:
* Create a new folder at some pre-specified location, add files for real world situation, free body diagram, assumptions and reasons etc.
* Test if these are detected by the program and can be included for the test.

**Comment by MitaliBhiwande** [comment]
Okay. But this particular user story deals with the basic idea of creating the test and not not adding a new question to the test. For adding a new question we have another user story where the above things you mentioned would work :)

**Comment by bakshizaki** [comment]
Alright, seems good. Also when we are done with a story just close the issue. Adding done is also a good idea but can be optional.

**Comment by MitaliBhiwande** [comment]
Okay.Closing this issue. 👍
